version: "3.9"

services:
  load-balancer:
    build:
      context: .
      dockerfile: "LoadBalancer/Dockerfile"
    ports:
      - 9002:80
    depends_on:
      - api
  api:
    build:
      context: .
      dockerfile: "WebAPI/Dockerfile"
    volumes:
      - ./WebAPI/Data:/data 
    deploy:
      replicas: 3
  angular:
    build:
      context: ./SearchEngine-Frontend
      dockerfile: ./Dockerfile
    ports:
      - 9001:80
    depends_on:
      - load-balancer
    
    
