version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: "WebAPI/Dockerfile"
    ports:
      - 9000:80
    volumes:
      - C:/GitHub/SearchEngine-Baseline/WebAPI/Data:/data 
  angular:
    build:
      context: ./SearchEngine-Frontend
      dockerfile: ./Dockerfile
    ports:
      - 9001:80
    
    
