version: "3.9"

services:
  load-balancer:
    build:
      context: .
      dockerfile: "LoadBalancer/Dockerfile"
    image: chrlindholm/search-engine-load-balancer:${DEPLOY_NUMBER}
    ports:
      - 9000:80
  api:
    build:
      context: .
      dockerfile: "WebAPI/Dockerfile"
    image: chrlindholm/search-engine-api:${DEPLOY_NUMBER}
    volumes:
      - ./WebAPI/Data:/data 
    deploy:
      replicas: 3
    depends_on:
      - load-balancer
  angular:
    build:
      context: ./SearchEngine-Frontend
      dockerfile: ./Dockerfile
    image: chrlindholm/search-engine-angular:${DEPLOY_NUMBER}
    ports:
      - 9001:80
    depends_on:
      - load-balancer
  userservice:
    build:
      context: .
      dockerfile: "UserServiceAPI/Dockerfile"
    image: chrlindholm/search-engine-userservice:${DEPLOY_NUMBER}
    volumes:
      - ./UserServiceAPI/Data:/data
    deploy:
      replicas: 3
    depends_on:
      - load-balancer

    
    
